Zzzul:
  name: Mohammad Zulfahmi
  description: Creator
  avatar: https://avatars.githubusercontent.com/u/62506582
rachyharkov:
  name: Rachmad Nur Hayat
  description: Co-Creator
  avatar: https://avatars.githubusercontent.com/u/44340813